-   id: mocha
    name: mocha
    entry: my-cmd-mod.sh
    language: node
    files: "**/*"
    args: []


    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0
