-   id: my-cmd-mod
    name: 'my-cmd-mod'
    entry: my-cmd-mod.sh
    language: script
    files: \.(ts|tsx)$
    args: []


    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0
